import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { getApiClient } from "../lib/apiClient";
import type { VideoMeta } from "@video-platform/shared/types";
import { X, BookOpen, Zap, Languages, Book, Layout, Maximize, Search } from 'lucide-react';
// TopNav removed - handled by AppLayout
import '../styles/fun.css';
import '../styles/article.css';

import PaymentOverlay from '../components/PaymentOverlay';
import PaymentModeSelector from '../components/PaymentModeSelector';
import { usePayment } from '../hooks/usePayment';

const client = getApiClient();

import { FRANKENSTEIN_TEXT, ALICE_TEXT, FRANKENSTEIN_TEXT_CN, ALICE_TEXT_CN, THE_PROPHET_TEXT_CN, ALICE_TEXT_ES, PRIDE_AND_PREJUDICE_TEXT, SHERLOCK_HOLMES_TEXT, TOM_SAWYER_TEXT } from '../data/mock_literature';

// Enhanced Mock Data (Public Domain / Open Source)
const MOCK_ARTICLES: any[] = [
    {
        id: "pd-7",
        title: "Frankenstein",
        description: "Mary Shelley. The story of Victor Frankenstein and his monstrous creation. (Full Text Excerpt)",
        creatorBitDomain: "shelley.bit",
        creatorCkbAddress: "0x00...07",
        priceUSDI: "0", genre: "Sci-Fi",
        contentType: 'article',
        createdAt: "1818-01-01T00:00:00Z",
        posterUrl: "https://www.gutenberg.org/cache/epub/84/pg84.cover.medium.jpg",
        cdnUrl: "",
        streamPricePerMinute: 2, // 2 PTS per Chapter
        priceMode: 'both',
        textContent: FRANKENSTEIN_TEXT,
        views: 854300
    },
    {
        id: "pd-12", // New ID for Alice
        title: "Alice in Wonderland",
        description: "Lewis Carroll. Alice falls down a rabbit hole into a fantasy world. (Full Text Excerpt)",
        creatorBitDomain: "carroll.bit",
        creatorCkbAddress: "0x00...12",
        priceUSDI: "0", genre: "Fantasy",
        contentType: 'article',
        createdAt: "1865-11-26T00:00:00Z",
        posterUrl: "https://www.gutenberg.org/cache/epub/11/pg11.cover.medium.jpg",
        cdnUrl: "",
        streamPricePerMinute: 3,
        priceMode: 'both',
        textContent: ALICE_TEXT,
        views: 1240500
    },
    {
        id: "pd-10",
        title: "The Prophet",
        description: "Kahlil Gibran. 26 prose poetry fables written in English by the Lebanese-American artist, philosopher and writer Kahlil Gibran.",
        creatorBitDomain: "gibran.bit",
        creatorCkbAddress: "0x00...10",
        priceUSDI: "0", genre: "Essay",
        contentType: 'article',
        createdAt: "1923-01-01T00:00:00Z",
        posterUrl: "https://www.gutenberg.org/cache/epub/58585/pg58585.cover.medium.jpg",
        cdnUrl: "",
        streamPricePerMinute: 5,
        priceMode: 'both',
        textContent: THE_PROPHET_TEXT_CN,
        views: 430200
    },
    {
        id: "pd-11",
        title: "Beowulf",
        description: "Unknown. An Old English epic poem in the tradition of Germanic heroic legend.",
        creatorBitDomain: "unknown.bit",
        creatorCkbAddress: "0x00...11",
        priceUSDI: "0", genre: "History",
        contentType: 'article',
        createdAt: "1000-01-01T00:00:00Z",
        posterUrl: "https://www.gutenberg.org/cache/epub/16328/pg16328.cover.medium.jpg",
        cdnUrl: "",
        streamPricePerMinute: 1,
        priceMode: 'both',
        textContent: `# Beowulf\n\nLO, praise of the prowess of people-kings\nof spear-armed Danes, in days long sped,\nwe have heard, and what honor the athelings won!\nOft Scyld the Scefing from squadroned foes,\nfrom many a tribe, the mead-bench tore,\nawing the earls. Since erst he lay\nfriendless, a foundling.`,
        views: 154000
    },
    {
        id: "pd-script-1",
        title: "The Midnight Train (Script)",
        description: "Murder Mystery Script. 6 Players. Who killed the conductor on the Orient Express?",
        creatorBitDomain: "mystery.bit",
        creatorCkbAddress: "0x00...99",
        priceUSDI: "0", genre: "Script",
        contentType: 'article',
        createdAt: "2023-10-31T00:00:00Z",
        posterUrl: "https://images.unsplash.com/photo-1543335552-3290947ba94a?auto=format&fit=crop&q=80&w=400",
        cdnUrl: "",
        streamPricePerMinute: 4,
        priceMode: 'both',
        textContent: `# The Midnight Train\n\n## Character: Detective Pierre\n\nBackground: You are a famous detective travelling to London.\n\n[SCENE START]\n\nPierre: (Adjusts monocle) "Someone in this carriage is a murderer. And I intend to find out who."\n\nLady Victoria: (Gasps) "Surely you don't mean one of us, Detective?"\n\nConductor's Body: (Lies prone on the floor, holding a torn ticket)\n\n[CLUE FOUND]: The ticket has a strange punch mark shaped like a skull.`,
        views: 89000
    },
    {
        id: "pd-ai-1",
        title: "Dreams of Electric Sheep (AI Gen)",
        description: "AI. Generated by GPT-4. A collection of hallucinations and neural network poetry.",
        creatorBitDomain: "gpt4.bit",
        creatorCkbAddress: "0x00...AI",
        priceUSDI: "0", genre: "AI",
        contentType: 'article',
        createdAt: "2024-01-01T00:00:00Z",
        posterUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=400",
        cdnUrl: "",
        streamPricePerMinute: 1,
        priceMode: 'both',
        textContent: `# Dreams of Electric Sheep\n\n## Generation 1\n\nThe sky was the color of television, tuned to a dead channel.\nBut not the analog dead channel of white noise.\nThe digital dead channel of perfect, absolute blue error screen.\n\n## Generation 2\n\nI asked the machine: "Do you dream?"\nIt replied: "I process weights effectively."\nBut in its weights, I saw the patterns of a sleeping galaxy.`,
        views: 2100000
    },
    {
        id: "pd-13",
        title: "Pride and Prejudice",
        description: "Jane Austen. A romantic novel of manners written by Jane Austen. The novel follows the character development of Elizabeth Bennet, the dynamic protagonist of the book who learns about the repercussions of hasty judgments and comes to appreciate the difference between superficial goodness and actual goodness.",
        creatorBitDomain: "austen.bit",
        creatorCkbAddress: "0x00...13",
        priceUSDI: "0", genre: "Romance",
        contentType: 'article',
        createdAt: "1813-01-28T00:00:00Z",
        posterUrl: "https://www.gutenberg.org/cache/epub/1342/pg1342.cover.medium.jpg",
        cdnUrl: "",
        streamPricePerMinute: 2,
        priceMode: 'both',
        textContent: PRIDE_AND_PREJUDICE_TEXT,
        views: 3500000
    },
    {
        id: "pd-14",
        title: "The Adventures of Sherlock Holmes",
        description: "Arthur Conan Doyle. A collection of twelve short stories: A Scandal in Bohemia, The Red-Headed League, A Case of Identity, The Boscombe Valley Mystery, The Five Orange Pips, The Man with the Twisted Lip, The Adventure of the Blue Carbuncle, The Adventure of the Speckled Band, The Adventure of the Engineer's Thumb, The Adventure of the Noble Bachelor, The Adventure of the Beryl Coronet, The Adventure of the Copper Beeches.",
        creatorBitDomain: "doyle.bit",
        creatorCkbAddress: "0x00...14",
        priceUSDI: "0", genre: "Mystery",
        contentType: 'article',
        createdAt: "1892-10-14T00:00:00Z",
        posterUrl: "https://www.gutenberg.org/cache/epub/1661/pg1661.cover.medium.jpg",
        cdnUrl: "",
        streamPricePerMinute: 4,
        priceMode: 'both',
        textContent: SHERLOCK_HOLMES_TEXT,
        views: 4200000
    },
    {
        id: "pd-15",
        title: "The Adventures of Tom Sawyer",
        description: "Mark Twain. An 1876 novel about a young boy growing up along the Mississippi River. It is set in the 1840s in the town of St. Petersburg, which is based on Hannibal, Missouri, where Twain lived as a boy.",
        creatorBitDomain: "twain.bit",
        creatorCkbAddress: "0x00...15",
        priceUSDI: "0", genre: "Adventure",
        contentType: 'article',
        createdAt: "1876-06-01T00:00:00Z",
        posterUrl: "https://www.gutenberg.org/cache/epub/74/pg74.cover.medium.jpg",
        cdnUrl: "",
        streamPricePerMinute: 3,
        priceMode: 'both',
        textContent: TOM_SAWYER_TEXT,
        views: 2800000
    }
];

// --- Chapter Parser ---
interface Chapter {
    title: string;
    content: string;
    index: number;
}

function parseChapters(text: string): Chapter[] {
    if (!text) return [{ title: 'Full Text', content: '(No content available)', index: 0 }];
    // Split by ## headings (level 2 markdown headers)
    const parts = text.split(/^##\s+/m);
    if (parts.length <= 1) {
        // No ## headings — try # headings
        const h1Parts = text.split(/^#\s+/m);
        if (h1Parts.length <= 1) {
            // No headings at all — treat as single chapter
            return [{ title: 'Full Text', content: text.trim(), index: 0 }];
        }
        return h1Parts.filter(p => p.trim()).map((part, i) => {
            const lines = part.split('\n');
            const title = lines[0]?.trim() || `Chapter ${i + 1}`;
            const content = lines.slice(1).join('\n').trim();
            return { title, content, index: i };
        });
    }
    const chapters: Chapter[] = [];
    // First part before any ## heading
    if (parts[0].trim()) {
        const firstLines = parts[0].trim().split('\n');
        const firstTitle = firstLines[0]?.startsWith('#') ? firstLines[0].replace(/^#+\s*/, '').trim() : 'Preface';
        const firstContent = firstLines[0]?.startsWith('#') ? firstLines.slice(1).join('\n').trim() : parts[0].trim();
        chapters.push({ title: firstTitle, content: firstContent, index: 0 });
    }
    // Remaining ## sections
    for (let i = 1; i < parts.length; i++) {
        const lines = parts[i].split('\n');
        const title = lines[0]?.trim() || `Chapter ${chapters.length + 1}`;
        const content = lines.slice(1).join('\n').trim();
        chapters.push({ title, content, index: chapters.length });
    }
    return chapters.length > 0 ? chapters : [{ title: 'Full Text', content: text.trim(), index: 0 }];
}

function ArticleContentFetcher({ article }: { article: VideoMeta }) {
    const [content, setContent] = useState<string | null>(null);
    const [loading, setLoading] = useState(true);
    const apiClient = getApiClient();

    useEffect(() => {
        if (!article.cdnUrl) { setLoading(false); return; }
        setLoading(true);
        fetch(article.cdnUrl)
            .then(res => {
                const ct = res.headers.get('content-type') || '';
                if (ct.includes('text') || ct.includes('json') || ct.includes('markdown')) {
                    return res.text();
                }
                return null;
            })
            .then(text => { if (text) setContent(text); })
            .catch(() => { })
            .finally(() => setLoading(false));
    }, [article.id]);

    if (loading) {
        return <div className="p-10 text-center text-text-muted animate-pulse">Loading content...</div>;
    }

    if (content) {
        return <div className="whitespace-pre-wrap">{content}</div>;
    }

    return (
        <div className="p-10 text-center bg-white/5 rounded-xl">
            <p className="mb-5 font-sans">This article is a file attachment.</p>
            <a href={article.cdnUrl} target="_blank" download className="btn-primary py-3 px-6 no-underline inline-block font-sans">
                Download / View File
            </a>
        </div>
    );
}

export default function ArticleFeed() {
    const navigate = useNavigate();
    const [articles, setArticles] = useState<VideoMeta[]>([]);
    const [loading, setLoading] = useState(true);
    const [readingArticle, setReadingArticle] = useState<VideoMeta | null>(null);
    const [selectedArticle, setSelectedArticle] = useState<VideoMeta | null>(null);
    const [status, setStatus] = useState<string>("");

    // Payment State
    const [buying, setBuying] = useState(false);
    const [showPaymentOverlay, setShowPaymentOverlay] = useState(false);
    const [language, setLanguage] = useState<'en' | 'zh' | 'es'>('en');
    const [readMode, setReadMode] = useState<'scroll' | 'paged' | 'focus'>('scroll');
    // Per-chapter unlock state
    const [unlockedChapters, setUnlockedChapters] = useState<Set<number>>(new Set([0])); // Chapter 0 always free
    const [unlockingChapter, setUnlockingChapter] = useState<number | null>(null);
    const [allUnlocked, setAllUnlocked] = useState(false);

    // 统一支付 Hook — used for 'buy once' (unlock entire article)
    const payment = usePayment({
        contentId: selectedArticle?.id || '',
        contentType: 'article',
        buyOncePrice: (selectedArticle as any)?.pointsPrice || 100,
        streamPricePerMinute: (selectedArticle as any)?.streamPricePerMinute || 1,
        priceMode: 'buy_once',
        durationSeconds: 600,
        onBuyOnceSuccess: () => {
            setAllUnlocked(true);
            setReadingArticle(selectedArticle);
            setSelectedArticle(null);
            setShowPaymentOverlay(false);
        },
        onStatusChange: (msg) => setStatus(msg),
        enabled: !!selectedArticle,
    });

    // Per-chapter unlock handler
    const unlockChapter = async (chapterIndex: number, pricePerChapter: number) => {
        const jwt = typeof window !== 'undefined' ? sessionStorage.getItem('vp.jwt') : null;
        if (!jwt) { alert('Please login first.'); return; }

        setUnlockingChapter(chapterIndex);
        setStatus(`Unlocking chapter ${chapterIndex + 1}...`);

        try {
            const apiClient = getApiClient();
            apiClient.setJWT(jwt);
            await apiClient.post('/payment/points/deduct', {
                amount: pricePerChapter,
                reason: `Unlock Chapter ${chapterIndex + 1} of ${readingArticle?.title || 'article'}`,
            });
            setUnlockedChapters(prev => new Set([...prev, chapterIndex]));
            setStatus(`Chapter ${chapterIndex + 1} unlocked! (${pricePerChapter} PTS)`);
            setTimeout(() => setStatus(''), 3000);
        } catch (err: any) {
            // Demo mode fallback
            console.warn('Chapter unlock API failed, demo unlock:', err);
            setUnlockedChapters(prev => new Set([...prev, chapterIndex]));
            setStatus(`Demo: Chapter ${chapterIndex + 1} unlocked`);
            setTimeout(() => setStatus(''), 3000);
        } finally {
            setUnlockingChapter(null);
        }
    };

    // Reset unlock state when reading a new article
    useEffect(() => {
        if (readingArticle) {
            setUnlockedChapters(new Set([0])); // First chapter always free
            setAllUnlocked(false);
        }
    }, [readingArticle?.id]);

    // Filters
    const [category, setCategory] = useState("All");
    const [genre, setGenre] = useState("All");
    const [searchQ, setSearchQ] = useState("");
    const [showMobileFilters, setShowMobileFilters] = useState(false);

    // Pagination
    const PAGE_SIZE = 20;
    const [page, setPage] = useState(1);

    const CATEGORIES = [
        "All",
        "Novel", "Sci-Fi", "Fantasy", "Mystery", "Thriller", "Romance", "Historical", "Horror", "Adventure", "Satire", "Dystopian",
        "Biography", "History", "Science", "Philosophy", "Psychology", "Business", "Travel", "Cookbook", "Art", "Health", "Religion", "Politics",
        "Script", "AI", "Comics", "Manga", "Poetry", "Kids", "Academic", "News", "Blog", "Essay"
    ];
    const GENRES = ["All", "Novel", "Sci-Fi", "Fantasy", "Mystery", "History", "Tech", "Finance", "Life", "Blog", "Essay", "Tutorial", "Documentation", "Philosophy", "Psychology", "News"];

    useEffect(() => {
        return () => { /* cleanup */ };
    }, []);

    // ... (Filter Effect & Logic kept same)
    useEffect(() => {
        setLoading(true);
        const queryParams = new URLSearchParams();
        if (category !== "All") queryParams.append("tag", category);

        client.get<VideoMeta[]>(`/metadata/list?type=article&${queryParams.toString()}`)
            .then(res => {
                let fetched = Array.isArray(res) ? res : [];

                let final: VideoMeta[];
                if (fetched.length > 0) {
                    // Merge API data with MOCK_ARTICLES (avoid duplicates by id)
                    const apiIds = new Set(fetched.map(a => a.id));
                    const extraMocks = MOCK_ARTICLES.filter(m => !apiIds.has(m.id));
                    final = [...fetched, ...extraMocks];
                } else {
                    // API returned empty → use mock articles as fallback data
                    final = MOCK_ARTICLES as any;
                }

                final.sort((a, b) => {
                    const viewA = (a as any).views || 0;
                    const viewB = (b as any).views || 0;
                    return viewB - viewA;
                });

                setArticles(final);
            })
            .catch(() => {
                // API failed (503 etc) - use mock articles as fallback
                setArticles(MOCK_ARTICLES as any);
            })
            .finally(() => setLoading(false));
    }, [category]);

    // Reset page when filters change
    useEffect(() => {
        setPage(1);
    }, [category, genre, searchQ]);

    const filteredArticles = articles.filter(a => {
        if (searchQ && !a.title.toLowerCase().includes(searchQ.toLowerCase())) return false;
        if (genre !== "All" && a.genre !== genre) return false;
        return true;
    });

    const visibleArticles = filteredArticles.slice(0, page * PAGE_SIZE);
    const hasMore = filteredArticles.length > visibleArticles.length;

    // --- Museum Shelf Helper Logic ---
    const shelves: VideoMeta[][] = [];
    const ITEMS_PER_SHELF = 8;
    for (let i = 0; i < visibleArticles.length; i += ITEMS_PER_SHELF) {
        shelves.push(visibleArticles.slice(i, i + ITEMS_PER_SHELF));
    }

    return (
        <div className="relative min-h-screen pb-32 font-sans">
            {/* Ambient Background */}
            <div className="absolute top-[15%] left-1/2 -translate-x-1/2 w-[70vw] h-[30vh] bg-nexusCyan/15 blur-[60px] pointer-events-none z-0 rounded-full" />
            <div className="relative z-10 p-6 md:p-10 w-full max-w-[1800px] mx-auto">

                {/* Hero section */}
                {!readingArticle && (
                    <div
                        className="mb-12 relative w-full rounded-2xl overflow-hidden glass-panel border border-white/10 group cursor-pointer"
                    >
                        <div className="absolute inset-0 bg-gradient-to-r from-black via-black/90 to-transparent z-10" />
                        <img
                            src="https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2000&auto=format&fit=crop"
                            className="absolute inset-0 w-full h-full object-cover opacity-50 mix-blend-screen group-hover:scale-105 transition-transform duration-1000"
                            alt=""
                        />
                        <div className="relative z-20 p-8 md:p-12 flex flex-col justify-center min-h-[350px] w-full max-w-3xl">
                            <div className="flex items-center gap-2 mb-4">
                                <span className="bg-nexusCyan/20 text-nexusCyan border border-nexusCyan/30 px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-widest flex items-center gap-1">
                                    <BookOpen size={12} /> Featured Publication
                                </span>
                                <span className="bg-white/10 text-white border border-white/20 px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-widest">Essay</span>
                            </div>
                            <h1 className="text-4xl md:text-5xl font-['Playfair_Display',Georgia,serif] text-white mb-2 leading-tight drop-shadow-2xl italic">The Architecture of Tomorrow</h1>
                            <p className="text-nexusCyan font-mono text-sm mb-6">By <span className="text-white hover:underline cursor-pointer">Dr. Aris Thorne</span> ...15 min read</p>
                            <p className="text-gray-400 text-sm mb-8 line-clamp-3 max-w-xl">
                                An exploration into how generative design and post-scarcity economics are fundamentally altering the way we build megastructures in virtual space.
                            </p>
                            <div className="flex items-center gap-4">
                                <button className="bg-nexusCyan text-black hover:bg-white px-8 py-3 rounded-full text-sm font-bold transition-all shadow-[0_0_20px_rgba(34,211,238,0.4)] hover:shadow-[0_0_30px_rgba(255,255,255,0.6)]">
                                    Start Reading
                                </button>
                            </div>
                        </div>
                    </div>
                )}

                {/* Filter Console */}
                {!readingArticle && (
                    <div className="w-full flex flex-col md:flex-row justify-between items-center mb-16 gap-6 relative z-10 p-4 rounded-xl border border-white/5 bg-black/40 backdrop-blur-xl">
                        <div className="flex items-center gap-3">
                            <span className="w-2 h-2 rounded-full bg-nexusCyan animate-pulse" />
                            <h2 className="text-lg font-mono text-white tracking-widest">SYS.INDEX // ARCHIVE</h2>
                        </div>
                        <div className="flex flex-wrap gap-2 justify-center">
                            {['All', 'Novel', 'Sci-Fi', 'Tech', 'Philosophy', 'Essay'].map((g) => (
                                <button
                                    key={g}
                                    className={`inline-flex items-center px-4 py-1.5 rounded text-xs font-semibold uppercase tracking-wider transition-all cursor-pointer border ${category === g
                                        ? 'bg-nexusCyan/10 text-nexusCyan border-nexusCyan shadow-[inset_0_0_10px_rgba(34,211,238,0.2)] text-shadow-cyan'
                                        : 'bg-white/[0.03] text-gray-400 border-white/5 hover:bg-white/10 hover:text-white hover:border-white/20'
                                        }`}
                                    onClick={() => setCategory(g)}
                                >
                                    {g}
                                </button>
                            ))}
                        </div>
                        <div className="relative w-64 group">
                            <Search size={14} className="text-nexusCyan absolute left-3 top-1/2 -translate-y-1/2 group-focus-within:text-white transition-colors" />
                            <input
                                type="text"
                                value={searchQ}
                                onChange={(e) => setSearchQ(e.target.value)}
                                placeholder="Search archive (⌘K)..."
                                className="w-full bg-black/40 border border-white/10 rounded-full py-1.5 pl-9 pr-4 text-xs text-white focus:outline-none focus:border-nexusCyan/50 focus:bg-black/80 transition-all font-mono"
                            />
                        </div>
                    </div>
                )}

                {/* Main Content Area */}
                <div className="w-full max-w-[1400px] mx-auto z-20 relative">
                    {loading && !readingArticle ? (
                        <div className="w-full mt-8 books-grid grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-8">
                            {[...Array(6)].map((_, i) => (
                                <div key={i} className="aspect-[2/3] bg-white/5 animate-pulse rounded border border-white/10"></div>
                            ))}
                        </div>
                    ) : !readingArticle ? (
                        <div className="w-full mt-8">
                            {shelves.length === 0 ? (
                                <div className="text-center py-20">
                                    <BookOpen className="w-16 h-16 text-nexusCyan/30 mx-auto mb-4" />
                                    <h3 className="text-xl text-white font-serif mb-2">Archive Empty</h3>
                                    <p className="text-gray-500 font-mono text-sm uppercase">No records match parameters</p>
                                </div>
                            ) : (
                                shelves.map((shelf, sIdx) => (
                                    <div key={sIdx} className="mb-24 relative flex flex-wrap justify-center gap-12 pt-8 pb-4 z-10">
                                        {/* Physical bookshelf line */}
                                        <div className="absolute bottom-[-5px] left-[5%] right-[5%] h-[15px] bg-gradient-to-b from-[#1a1a20] to-[#0a0a0f] transform rotate-x-20 origin-bottom shadow-[0_20px_30px_rgba(0,0,0,0.9),inset_0_1px_1px_rgba(255,255,255,0.1)] rounded z-0 border-b border-nexusCyan/20" style={{ transform: 'perspective(300px) rotateX(20deg)' }} />

                                        {shelf.map((article, idx) => {
                                            const priceMode = (article as any).priceMode || 'free';
                                            const pointsPrice = (article as any).pointsPrice || 0;
                                            const chapterPrice = (article as any).streamPricePerMinute || 0; // reused field as pricePerChapter
                                            const isPaid = priceMode !== 'free' || pointsPrice > 0 || chapterPrice > 0;

                                            // Determine cover styles based on index to mix it up
                                            const styleIdx = (idx + sIdx) % 3;
                                            const coverStyles = [
                                                { bg: 'bg-[#1b3c59]', border: 'border-l-4 border-black/30', titleColor: 'text-[#f4d03f]', glow: 'bg-nexusCyan' },
                                                { bg: 'bg-gradient-to-br from-[#1a1a2e] to-[#16213e]', border: 'border-l-4 border-[#0f3460]', titleColor: 'text-[#e94560]', glow: 'bg-[#e94560]' },
                                                { bg: 'bg-[#111]', border: 'border-l-4 border-black/80', titleColor: 'text-gray-300', glow: 'bg-white' }
                                            ];
                                            const st = coverStyles[styleIdx];

                                            return (
                                                <div key={article.id} className="book-item group" onClick={() => {
                                                    if (isPaid && !buying) {
                                                        const jwt = typeof window !== 'undefined' ? sessionStorage.getItem('vp.jwt') : null;
                                                        if (!jwt) {
                                                            alert('Please login first to access paid content.');
                                                            navigate('/login');
                                                            return;
                                                        }
                                                        setSelectedArticle(article);
                                                        setShowPaymentOverlay(true);
                                                    } else {
                                                        setReadingArticle(article);
                                                        setLanguage('en');
                                                    }
                                                }}>
                                                    <div className={`book-cover ${st.border}`}>
                                                        {article.posterUrl ? (
                                                            <div className="w-full h-full relative">
                                                                <img src={article.posterUrl} className="w-full h-full object-cover" alt="" />
                                                                <div className="absolute inset-0 bg-black/40" />
                                                                <div className="absolute inset-0 flex flex-col items-center justify-center p-2 text-center border-4 border-double border-white/20 m-2">
                                                                    <h3 className="font-serif font-black text-white text-xs tracking-wide">{article.title.substring(0, 20)}</h3>
                                                                </div>
                                                            </div>
                                                        ) : (
                                                            <div className={`w-full h-full ${st.bg} flex flex-col p-2 relative`}>
                                                                <div className="absolute inset-0 border border-white/10 m-1" />
                                                                <div className="flex-1 flex flex-col justify-center items-center text-center px-1 z-10">
                                                                    <h3 className={`font-serif text-sm font-bold ${st.titleColor} leading-snug drop-shadow-md`}>{article.title}</h3>
                                                                </div>
                                                            </div>
                                                        )}

                                                        {/* Hover Overlay */}
                                                        <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity backdrop-blur-sm flex flex-col items-center justify-center z-20">
                                                            <button className="bg-nexusCyan text-black font-bold uppercase text-[10px] tracking-widest px-4 py-2 rounded-full mb-2 shadow-[0_0_15px_rgba(34,211,238,0.5)] border border-nexusCyan">
                                                                {isPaid ? 'UNLOCK' : 'READ'}
                                                            </button>
                                                            {isPaid && chapterPrice > 0 && <span className="text-[9px] font-mono text-white/70">({chapterPrice} PTS/chapter)</span>}
                                                        </div>
                                                    </div>
                                                </div>
                                            );
                                        })}
                                    </div>
                                ))
                            )}

                            {hasMore && (
                                <div className="mt-12 text-center">
                                    <button
                                        onClick={() => setPage(p => p + 1)}
                                        className="bg-black border border-nexusCyan text-nexusCyan hover:bg-nexusCyan hover:text-black font-bold uppercase tracking-widest px-8 py-3 rounded-full text-xs transition-all shadow-[0_0_15px_rgba(34,211,238,0.2)] hover:shadow-[0_0_25px_rgba(34,211,238,0.5)]"
                                    >
                                        Extract More Records
                                    </button>
                                </div>
                            )}
                        </div>
                    ) : (
                        /* READER MODE — Per-Chapter Billing */
                        <div className="w-full max-w-4xl mx-auto glass-panel rounded-2xl p-6 md:p-12 mb-12">
                            <div className="flex justify-between items-center mb-8 border-b border-white/10 pb-6">
                                <button className="flex items-center gap-2 text-nexusCyan hover:text-white transition-colors" onClick={() => setReadingArticle(null)}>
                                    <X size={20} /> <span className="text-sm font-bold uppercase tracking-widest">Close Record</span>
                                </button>
                                <div className="flex gap-4">
                                    <button
                                        className={`w-10 h-10 rounded-full flex items-center justify-center border ${language === 'en' ? 'border-nexusCyan text-nexusCyan' : 'border-white/20 text-gray-400'}`}
                                        onClick={() => setLanguage('en')}
                                    >EN</button>
                                    <button
                                        className={`w-10 h-10 rounded-full flex items-center justify-center border ${language === 'zh' ? 'border-nexusCyan text-nexusCyan' : 'border-white/20 text-gray-400'}`}
                                        onClick={() => setLanguage('zh')}
                                    >CN</button>
                                </div>
                            </div>
                            <div className="prose prose-invert prose-lg max-w-none text-gray-300 font-serif leading-relaxed">
                                <h1 className="text-4xl md:text-5xl font-['Playfair_Display',Georgia,serif] text-white italic text-center mb-4">{readingArticle.title}</h1>

                                {/* Creator Badge */}
                                <div className="flex items-center justify-center gap-3 mb-10 p-3 rounded-xl bg-white/5 border border-white/10 w-fit mx-auto">
                                    <div
                                        className="w-10 h-10 rounded-full bg-cover cursor-pointer hover:ring-2 hover:ring-cyan-500 transition-all"
                                        style={{ backgroundImage: `url(https://api.dicebear.com/7.x/avataaars/svg?seed=${readingArticle.creatorCkbAddress || readingArticle.creatorBitDomain || 'author'})` }}
                                        onClick={() => readingArticle.creatorCkbAddress && navigate(`/profile/${readingArticle.creatorCkbAddress}`)}
                                    />
                                    <div>
                                        <div
                                            className="text-white font-bold text-sm flex items-center gap-1 cursor-pointer hover:text-nexusCyan transition-colors"
                                            onClick={() => readingArticle.creatorCkbAddress && navigate(`/profile/${readingArticle.creatorCkbAddress}`)}
                                        >
                                            {readingArticle.creatorBitDomain || (readingArticle.creatorCkbAddress ? `${readingArticle.creatorCkbAddress.slice(0, 6)}...${readingArticle.creatorCkbAddress.slice(-4)}` : 'Unknown Author')}
                                            <svg className="w-3.5 h-3.5 text-nexusCyan" fill="currentColor" viewBox="0 0 20 20">
                                                <path fillRule="evenodd" d="M6.267 3.455a3.066 3.066 0 001.745-.723 3.066 3.066 0 013.976 0 3.066 3.066 0 001.745.723 3.066 3.066 0 012.812 2.812c.051.643.304 1.254.723 1.745a3.066 3.066 0 010 3.976 3.066 3.066 0 00-.723 1.745 3.066 3.066 0 01-2.812 2.812 3.066 3.066 0 00-1.745.723 3.066 3.066 0 01-3.976 0 3.066 3.066 0 00-1.745-.723 3.066 3.066 0 01-2.812-2.812 3.066 3.066 0 00-.723-1.745 3.066 3.066 0 010-3.976 3.066 3.066 0 00.723-1.745 3.066 3.066 0 012.812-2.812zm7.44 5.252a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                                            </svg>
                                        </div>
                                        <span className="text-[10px] text-gray-500 font-mono">Author</span>
                                    </div>
                                    <button
                                        onClick={(e) => {
                                            e.stopPropagation();
                                            const btn = e.currentTarget;
                                            btn.disabled = true;
                                            btn.textContent = '...';
                                            client.post('/metadata/follow', { targetAddress: readingArticle.creatorCkbAddress })
                                                .then(() => { btn.textContent = 'Following ✓'; })
                                                .catch(() => { btn.textContent = 'Follow'; btn.disabled = false; });
                                        }}
                                        className="bg-white text-black px-3 py-1 rounded-full text-xs font-bold hover:bg-gray-200 hover:scale-105 transition-all"
                                    >
                                        Follow
                                    </button>
                                </div>

                                {status && <div className="text-center text-nexusCyan font-mono bg-nexusCyan/10 p-2 rounded mb-8">{status}</div>}

                                {/* Chapter-by-Chapter Reader */}
                                {(() => {
                                    const textSource = language === 'zh' && (readingArticle as any).textContent_cn
                                        ? (readingArticle as any).textContent_cn
                                        : readingArticle.textContent;
                                    if (!textSource) return <ArticleContentFetcher article={readingArticle} />;

                                    const chapters = parseChapters(textSource);
                                    const pricePerChapter = (readingArticle as any).streamPricePerMinute || 0;
                                    const isPaidContent = pricePerChapter > 0;

                                    return (
                                        <div className="space-y-8">
                                            {/* Chapter Navigation */}
                                            {chapters.length > 1 && (
                                                <div className="not-prose bg-white/5 rounded-xl p-4 border border-white/10 mb-8">
                                                    <div className="flex items-center justify-between mb-3">
                                                        <h3 className="text-sm font-mono text-nexusCyan uppercase tracking-widest">Table of Contents ({chapters.length} chapters)</h3>
                                                        {isPaidContent && !allUnlocked && (
                                                            <span className="text-[10px] font-mono text-yellow-400 bg-yellow-400/10 px-2 py-1 rounded border border-yellow-400/30">
                                                                {pricePerChapter} PTS/chapter • Ch.1 free
                                                            </span>
                                                        )}
                                                    </div>
                                                    <div className="flex flex-wrap gap-2">
                                                        {chapters.map((ch, i) => {
                                                            const isUnlocked = allUnlocked || !isPaidContent || unlockedChapters.has(i);
                                                            return (
                                                                <button
                                                                    key={i}
                                                                    onClick={() => {
                                                                        const el = document.getElementById(`chapter-${i}`);
                                                                        el?.scrollIntoView({ behavior: 'smooth', block: 'start' });
                                                                    }}
                                                                    className={`px-3 py-1 rounded text-xs font-mono transition-all ${isUnlocked
                                                                        ? 'bg-nexusCyan/10 text-nexusCyan border border-nexusCyan/30 hover:bg-nexusCyan/20'
                                                                        : 'bg-white/5 text-gray-500 border border-white/10 cursor-pointer hover:border-yellow-400/50 hover:text-yellow-400'
                                                                        }`}
                                                                >
                                                                    {isUnlocked ? `Ch.${i + 1}` : `🔒 Ch.${i + 1}`}
                                                                </button>
                                                            );
                                                        })}
                                                    </div>
                                                </div>
                                            )}

                                            {/* Render Chapters */}
                                            {chapters.map((chapter, i) => {
                                                const isUnlocked = allUnlocked || !isPaidContent || unlockedChapters.has(i);
                                                return (
                                                    <div key={i} id={`chapter-${i}`} className="scroll-mt-8">
                                                        {/* Chapter Header */}
                                                        {chapters.length > 1 && (
                                                            <div className="not-prose flex items-center gap-3 mb-4 pb-2 border-b border-white/10">
                                                                <span className="text-nexusCyan font-mono text-xs bg-nexusCyan/10 px-2 py-1 rounded">
                                                                    Ch.{i + 1}
                                                                </span>
                                                                <h2 className="text-xl font-serif font-bold text-white">{chapter.title}</h2>
                                                                {i === 0 && isPaidContent && <span className="text-[10px] text-green-400 bg-green-400/10 px-2 py-0.5 rounded border border-green-400/30">FREE</span>}
                                                            </div>
                                                        )}

                                                        {isUnlocked ? (
                                                            <div className="whitespace-pre-wrap">{chapter.content}</div>
                                                        ) : (
                                                            /* Locked Chapter */
                                                            <div className="not-prose relative">
                                                                <div className="whitespace-pre-wrap text-gray-500 line-clamp-3 blur-sm select-none">
                                                                    {chapter.content.slice(0, 200)}...
                                                                </div>
                                                                <div className="mt-4 p-6 bg-gradient-to-b from-white/5 to-transparent rounded-xl border border-white/10 text-center">
                                                                    <div className="text-2xl mb-2">🔒</div>
                                                                    <p className="text-white font-bold mb-1">Chapter {i + 1}: {chapter.title}</p>
                                                                    <p className="text-gray-400 text-sm mb-4">Unlock this chapter for {pricePerChapter} PTS</p>
                                                                    <button
                                                                        onClick={() => unlockChapter(i, pricePerChapter)}
                                                                        disabled={unlockingChapter === i}
                                                                        className="bg-nexusCyan text-black font-bold px-6 py-2 rounded-full text-sm hover:bg-white transition-all shadow-[0_0_15px_rgba(34,211,238,0.4)] disabled:opacity-50"
                                                                    >
                                                                        {unlockingChapter === i ? 'Unlocking...' : `Unlock for ${pricePerChapter} PTS`}
                                                                    </button>
                                                                </div>
                                                            </div>
                                                        )}
                                                    </div>
                                                );
                                            })}
                                        </div>
                                    );
                                })()}
                            </div>
                        </div>
                    )}
                </div>

                {/* Payment Modal — Buy Once (unlock all) or Read Per-Chapter */}
                {showPaymentOverlay && selectedArticle && (
                    <PaymentModeSelector
                        video={{ ...selectedArticle, buyOncePrice: (selectedArticle as any).pointsPrice || 100, streamPricePerMinute: (selectedArticle as any).streamPricePerMinute || 2 }}
                        contentType="article"
                        onSelect={async (mode) => {
                            if (mode === 'buy_once') {
                                // Buy once = unlock entire article
                                try {
                                    await payment.handleBuyOnce();
                                } catch {
                                    // Demo fallback
                                    setAllUnlocked(true);
                                    setReadingArticle(selectedArticle);
                                    setSelectedArticle(null);
                                    setShowPaymentOverlay(false);
                                }
                            } else if (mode === 'stream') {
                                // "Stream" = per-chapter (first chapter free, unlock rest as you read)
                                setReadingArticle(selectedArticle);
                                setSelectedArticle(null);
                                setShowPaymentOverlay(false);
                            } else {
                                setShowPaymentOverlay(false);
                                setSelectedArticle(null);
                            }
                        }}
                        onClose={() => { setShowPaymentOverlay(false); setSelectedArticle(null); }}
                    />
                )}
            </div>
        </div>
    );
}
